name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  run-download-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install provengo
        uses: ./

      - name: run echo
        run: provengo run example/echo-api-server

      - name: report echo
        run: provengo report example/echo-api-server

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: products/reports