name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  run-download-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install provengo
        uses: ./

      - name: run provengo-project
        run: provengo run provengo/provengo-project

      - name: report provengo-project
        run: provengo report provengo/provengo-project

      - name: save report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: example/echo-api-server/products/reports