name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  run-download-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: echo
        uses: ./action
        with:
          command: 'echo "Executing command with parameters"'


      - name: Run My Download Action
        uses: ./action
        with:
          command: 'run'
          basic_parameters: '{"param1":"value1","param2":"value2"}'
          command_parameters: '{"paramA":"valueA","paramB":"valueB"}'